name: Continuous Integration

on:
  pull_request:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
